"""
UserRecommendation model for storing AI-generated song recommendations per user.
Stores recommendations generated by Gemini API with optional Spotify track enrichment.
"""

from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.sql import func
from app.database import Base


class UserRecommendation(Base):
    """Store AI-generated song recommendations per user."""

    __tablename__ = "user_recommendations"

    id = Column(Integer, primary_key=True, index=True)
    spotify_id = Column(String, nullable=False, index=True)
    batch_id = Column(String, nullable=False, index=True)
    title = Column(String, nullable=False)
    artist = Column(String, nullable=False)
    spotify_track_id = Column(String, nullable=True)
    generated_at = Column(DateTime, server_default=func.now())
